# Model Configuration
model:
  spatial_stream:
    backbone: resnet50
    pretrained: true
    num_classes: 10
  temporal_stream:
    backbone: resnet50
    pretrained: true
    num_classes: 10
  lstm:
    input_size: 20
    hidden_size: 128
    num_layers: 2
    num_classes: 10

# Optimizer Configuration
optimizer:
  type: Adam
  learning_rate: 0.001
  weight_decay: 0.0001

# Training Configuration
training:
  batch_size: 32
  num_epochs: 50
  log_interval: 10
  save_interval: 10
  checkpoint_dir: 'checkpoints/'

# Loss Function
loss:
  type: CrossEntropyLoss
